version: '3.4'
services:
  converters-nginx:
    networks:
      - converters-network
    container_name: converters-nginx
    image: nginx:1.21.5
    ports:
      - '3000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - converters-backend

  converters-backend:
    networks:
      - converters-network
    container_name: converters-backend
    build:
      context: ./../Converters
      dockerfile: ./Dockerfile.Web
    volumes:
      - files:/var/lib/images
    depends_on:
      - converters-db
      - converters-versions
    env_file:
      - backend.env

  converters-versions:
    networks:
      - converters-network
    container_name: converters-versions
    build:
      context: ./../Converters
      dockerfile: ./Dockerfile.Versions
    depends_on:
      - converters-db
    env_file:
      - versions.env

  converters-db:
    networks:
      - converters-network
    image: postgres:14.1
    container_name: converters-db
    ports:
      - '5432:5432'
    env_file:
      - postgres.env

networks:
  converters-network:
    
volumes:
  files: